using OpenXml.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DocumentFormat.OpenXml.Drawing.Diagrams
{
  [Alias("ConstraintType")]
  public enum ConstraintValues
  {
    [EnumString("none")]
    None = 0,
    [EnumString("alignOff")]
    AlignOff,
    [EnumString("begMarg")]
    BegMarg,
    [EnumString("bendDist")]
    BendDist,
    [EnumString("begPad")]
    BegPad,
    [EnumString("b")]
    B,
    [EnumString("bMarg")]
    BMarg,
    [EnumString("bOff")]
    BOff,
    [EnumString("ctrX")]
    CtrX,
    [EnumString("ctrXOff")]
    CtrXOff,
    [EnumString("ctrY")]
    CtrY,
    [EnumString("ctrYOff")]
    CtrYOff,
    [EnumString("connDist")]
    ConnDist,
    [EnumString("diam")]
    Diam,
    [EnumString("endMarg")]
    EndMarg,
    [EnumString("endPad")]
    EndPad,
    [EnumString("h")]
    H,
    [EnumString("hArH")]
    HArH,
    [EnumString("hOff")]
    HOff,
    [EnumString("l")]
    L,
    [EnumString("lMarg")]
    LMarg,
    [EnumString("lOff")]
    LOff,
    [EnumString("r")]
    R,
    [EnumString("rMarg")]
    RMarg,
    [EnumString("rOff")]
    ROff,
    [EnumString("primFontSz")]
    PrimFontSz,
    [EnumString("pyraAcctRatio")]
    PyraAcctRatio,
    [EnumString("secFontSz")]
    SecFontSz,
    [EnumString("sibSp")]
    SibSp,
    [EnumString("secSibSp")]
    SecSibSp,
    [EnumString("sp")]
    Sp,
    [EnumString("stemThick")]
    StemThick,
    [EnumString("t")]
    T,
    [EnumString("tMarg")]
    TMarg,
    [EnumString("tOff")]
    TOff,
    [EnumString("userA")]
    UserA,
    [EnumString("userB")]
    UserB,
    [EnumString("userC")]
    UserC,
    [EnumString("userD")]
    UserD,
    [EnumString("userE")]
    UserE,
    [EnumString("userF")]
    UserF,
    [EnumString("userG")]
    UserG,
    [EnumString("userH")]
    UserH,
    [EnumString("userI")]
    UserI,
    [EnumString("userJ")]
    UserJ,
    [EnumString("userK")]
    UserK,
    [EnumString("userL")]
    UserL,
    [EnumString("userM")]
    UserM,
    [EnumString("userN")]
    UserN,
    [EnumString("userO")]
    UserO,
    [EnumString("userP")]
    UserP,
    [EnumString("userQ")]
    UserQ,
    [EnumString("userR")]
    UserR,
    [EnumString("userS")]
    UserS,
    [EnumString("userT")]
    UserT,
    [EnumString("userU")]
    UserU,
    [EnumString("userV")]
    UserV,
    [EnumString("userW")]
    UserW,
    [EnumString("userX")]
    UserX,
    [EnumString("userY")]
    UserY,
    [EnumString("userZ")]
    UserZ,
    [EnumString("w")]
    W,
    [EnumString("wArH")]
    WArH,
    [EnumString("wOff")]
    WOff,
  }
}
