//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IML.ModelEdit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetamodelsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetamodelsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IML.ModelEdit.Resources.MetamodelsStrings", typeof(MetamodelsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metamodels.
        /// </summary>
        public static string _Metamodels {
            get {
                return ResourceManager.GetString("_Metamodels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract class.
        /// </summary>
        public static string AbstractClass {
            get {
                return ResourceManager.GetString("AbstractClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An abstract class cannot create elements, but can be used as a base type by other classes..
        /// </summary>
        public static string AbstractClass_Description_ {
            get {
                return ResourceManager.GetString("AbstractClass_Description_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        public static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly is a DLL that contains this model..
        /// </summary>
        public static string Assembly_Description_ {
            get {
                return ResourceManager.GetString("Assembly_Description_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly name.
        /// </summary>
        public static string AssemblyName {
            get {
                return ResourceManager.GetString("AssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of a DLL that contains this model..
        /// </summary>
        public static string AssemblyName_Description_ {
            get {
                return ResourceManager.GetString("AssemblyName_Description_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base type.
        /// </summary>
        public static string BaseType {
            get {
                return ResourceManager.GetString("BaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type from which this class inherits properties..
        /// </summary>
        public static string BaseType_Description_ {
            get {
                return ResourceManager.GetString("BaseType_Description_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete class property.
        /// </summary>
        public static string DeleteClassProperty {
            get {
                return ResourceManager.GetString("DeleteClassProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete class property &apos;{0}&apos;?.
        /// </summary>
        public static string DeleteClassPropertyConfirm_1 {
            get {
                return ResourceManager.GetString("DeleteClassPropertyConfirm_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete enum type.
        /// </summary>
        public static string DeleteEnumType {
            get {
                return ResourceManager.GetString("DeleteEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete enum type {0}?.
        /// </summary>
        public static string DeleteEnumTypeConfirm_1 {
            get {
                return ResourceManager.GetString("DeleteEnumTypeConfirm_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete enum value.
        /// </summary>
        public static string DeleteEnumValue {
            get {
                return ResourceManager.GetString("DeleteEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete enum value {0}?.
        /// </summary>
        public static string DeleteEnumValueConfirm_1 {
            get {
                return ResourceManager.GetString("DeleteEnumValueConfirm_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete metaclass.
        /// </summary>
        public static string DeleteMetaclass {
            get {
                return ResourceManager.GetString("DeleteMetaclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete metaclass {0}?.
        /// </summary>
        public static string DeleteMetaclassConfirm_1 {
            get {
                return ResourceManager.GetString("DeleteMetaclassConfirm_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete metamodel.
        /// </summary>
        public static string DeleteMetamodel {
            get {
                return ResourceManager.GetString("DeleteMetamodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete type.
        /// </summary>
        public static string DeleteType {
            get {
                return ResourceManager.GetString("DeleteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete type {0}?.
        /// </summary>
        public static string DeleteTypeConfirm_1 {
            get {
                return ResourceManager.GetString("DeleteTypeConfirm_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation for designers. It can contain references to other elements. .
        /// </summary>
        public static string Description_Description_ {
            get {
                return ResourceManager.GetString("Description_Description_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name is used in documents e.g. in specification tables. It can contain spaces and Unicode letters..
        /// </summary>
        public static string DisplayName_Description_ {
            get {
                return ResourceManager.GetString("DisplayName_Description_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit class property.
        /// </summary>
        public static string EditClassProperty {
            get {
                return ResourceManager.GetString("EditClassProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit enum type.
        /// </summary>
        public static string EditEnumType {
            get {
                return ResourceManager.GetString("EditEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit enum value.
        /// </summary>
        public static string EditEnumValue {
            get {
                return ResourceManager.GetString("EditEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit metaclass definition.
        /// </summary>
        public static string EditMetaclass {
            get {
                return ResourceManager.GetString("EditMetaclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit metamodel properties.
        /// </summary>
        public static string EditMetamodel {
            get {
                return ResourceManager.GetString("EditMetamodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit type definition.
        /// </summary>
        public static string EditType {
            get {
                return ResourceManager.GetString("EditType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum values are named values that can be assigned to a property.
        /// </summary>
        public static string EnumType_Values_Description_ {
            get {
                return ResourceManager.GetString("EnumType_Values_Description_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum values.
        /// </summary>
        public static string EnumType_Values_Hint_ {
            get {
                return ResourceManager.GetString("EnumType_Values_Hint_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value (integer).
        /// </summary>
        public static string EnumValue {
            get {
                return ResourceManager.GetString("EnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer value assigned to a name..
        /// </summary>
        public static string EnumValue_Description_ {
            get {
                return ResourceManager.GetString("EnumValue_Description_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum values can have integer values specified..
        /// </summary>
        public static string EnumValuesHint {
            get {
                return ResourceManager.GetString("EnumValuesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate code.
        /// </summary>
        public static string GenerateCode {
            get {
                return ResourceManager.GetString("GenerateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metaclass properies describe values that model element can hold..
        /// </summary>
        public static string Metaclass_Properties_Description_ {
            get {
                return ResourceManager.GetString("Metaclass_Properties_Description_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties marked with italic are inherited..
        /// </summary>
        public static string Metaclass_Properties_Hint_ {
            get {
                return ResourceManager.GetString("Metaclass_Properties_Hint_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metaclass properties.
        /// </summary>
        public static string MetaclassProperties {
            get {
                return ResourceManager.GetString("MetaclassProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metamodel &apos;{0}&apos; compilation errors.
        /// </summary>
        public static string MetamodelCompilationErrors_1 {
            get {
                return ResourceManager.GetString("MetamodelCompilationErrors_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metamodel &apos;{0}&apos; compiled. Library &apos;{1}&apos; created..
        /// </summary>
        public static string MetamodelCompiled_1 {
            get {
                return ResourceManager.GetString("MetamodelCompiled_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metamodels describe all available types of elements. Inheritance structure is shown in the tree view. Types marked with italic are abstract..
        /// </summary>
        public static string Metamodels_Description_ {
            get {
                return ResourceManager.GetString("Metamodels_Description_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types marked with italic are abstract..
        /// </summary>
        public static string MetamodelsHint {
            get {
                return ResourceManager.GetString("MetamodelsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modeling.
        /// </summary>
        public static string Modeling {
            get {
                return ResourceManager.GetString("Modeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of.
        /// </summary>
        public static string MultiProperty {
            get {
                return ResourceManager.GetString("MultiProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A property accepts many values..
        /// </summary>
        public static string MultiProperty_Description_ {
            get {
                return ResourceManager.GetString("MultiProperty_Description_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique identifier. Only latin letters are accepted..
        /// </summary>
        public static string Name_Description_ {
            get {
                return ResourceManager.GetString("Name_Description_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        public static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sequence of identifiers separated by dots. Distinguishes names of elements defined in this model from elements defined in other models..
        /// </summary>
        public static string Namespace_Description_ {
            get {
                return ResourceManager.GetString("Namespace_Description_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New class property.
        /// </summary>
        public static string NewClassProperty {
            get {
                return ResourceManager.GetString("NewClassProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New enum type.
        /// </summary>
        public static string NewEnumType {
            get {
                return ResourceManager.GetString("NewEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New enum value.
        /// </summary>
        public static string NewEnumValue {
            get {
                return ResourceManager.GetString("NewEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New metaclass.
        /// </summary>
        public static string NewMetaclass {
            get {
                return ResourceManager.GetString("NewMetaclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New metamodel.
        /// </summary>
        public static string NewMetamodel {
            get {
                return ResourceManager.GetString("NewMetamodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New subclass.
        /// </summary>
        public static string NewSubclass {
            get {
                return ResourceManager.GetString("NewSubclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property type.
        /// </summary>
        public static string PropertyType {
            get {
                return ResourceManager.GetString("PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type of data available in this property..
        /// </summary>
        public static string PropertyType_Description_ {
            get {
                return ResourceManager.GetString("PropertyType_Description_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference default constructor not implemented..
        /// </summary>
        public static string ReferenceDefaultConstructorError {
            get {
                return ResourceManager.GetString("ReferenceDefaultConstructorError", resourceCulture);
            }
        }
    }
}
