//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iml.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Iml.Resources.DataResources", typeof(DataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        internal static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        internal static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author ID.
        /// </summary>
        internal static string AuthorID {
            get {
                return ResourceManager.GetString("AuthorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed at.
        /// </summary>
        internal static string ClosedAt {
            get {
                return ResourceManager.GetString("ClosedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed by.
        /// </summary>
        internal static string ClosedBy {
            get {
                return ResourceManager.GetString("ClosedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        internal static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft SQL Server used.
        /// </summary>
        internal static string DatabaseKindMSSQLDescription {
            get {
                return ResourceManager.GetString("DatabaseKindMSSQLDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Access database used.
        /// </summary>
        internal static string DatabaseKindOLEDBDescription {
            get {
                return ResourceManager.GetString("DatabaseKindOLEDBDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string DatabaseKindUnknown {
            get {
                return ResourceManager.GetString("DatabaseKindUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source.
        /// </summary>
        internal static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source (DB server) giving access to the Solution.
        /// </summary>
        internal static string DataSourceDescription {
            get {
                return ResourceManager.GetString("DataSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution file (or catalog) name - without path and extension.
        /// </summary>
        internal static string DbCreateFileNameDescription {
            get {
                return ResourceManager.GetString("DbCreateFileNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should init information layer structure (data loaded from the template)?.
        /// </summary>
        internal static string DbCreateInitLayersDescription {
            get {
                return ResourceManager.GetString("DbCreateInitLayersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution engine selection.
        /// </summary>
        internal static string DbCreateKindDescription {
            get {
                return ResourceManager.GetString("DbCreateKindDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution internal name (used by SQL server).
        /// </summary>
        internal static string DbCreateNameDescription {
            get {
                return ResourceManager.GetString("DbCreateNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name (symbol) of the project created in the Solution.
        /// </summary>
        internal static string DbCreateProjectNameDescription {
            get {
                return ResourceManager.GetString("DbCreateProjectNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title of the project created in the Solution.
        /// </summary>
        internal static string DbCreateProjectTitleDescription {
            get {
                return ResourceManager.GetString("DbCreateProjectTitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should register author in the Solution (data loaded from the user Solution)?.
        /// </summary>
        internal static string DbCreateRegisterAuthorDescription {
            get {
                return ResourceManager.GetString("DbCreateRegisterAuthorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a Solution is created by admin then it may be created in the name of other user. That author will be responsible for this Solution..
        /// </summary>
        internal static string DbCreateResponsibleAuthorDescription {
            get {
                return ResourceManager.GetString("DbCreateResponsibleAuthorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbID.
        /// </summary>
        internal static string DbID {
            get {
                return ResourceManager.GetString("DbID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbName.
        /// </summary>
        internal static string DbName {
            get {
                return ResourceManager.GetString("DbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document first version creation date and time.
        /// </summary>
        internal static string DocumentCreatedAtDescription {
            get {
                return ResourceManager.GetString("DocumentCreatedAtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document first author&apos;s identifier.
        /// </summary>
        internal static string DocumentCreatedByDescription {
            get {
                return ResourceManager.GetString("DocumentCreatedByDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial name of the document.
        /// </summary>
        internal static string DocumentNameDescription {
            get {
                return ResourceManager.GetString("DocumentNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stereotype defines document template.
        /// </summary>
        internal static string DocumentStereotypeDescription {
            get {
                return ResourceManager.GetString("DocumentStereotypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globally unique identifier.
        /// </summary>
        internal static string GuidDescription {
            get {
                return ResourceManager.GetString("GuidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initials.
        /// </summary>
        internal static string Initials {
            get {
                return ResourceManager.GetString("Initials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should create layers.
        /// </summary>
        internal static string InitLayers {
            get {
                return ResourceManager.GetString("InitLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is closed?.
        /// </summary>
        internal static string IsClosed {
            get {
                return ResourceManager.GetString("IsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itls.
        /// </summary>
        internal static string Itls {
            get {
                return ResourceManager.GetString("Itls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        internal static string Kind {
            get {
                return ResourceManager.GetString("Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer ID.
        /// </summary>
        internal static string LayerID {
            get {
                return ResourceManager.GetString("LayerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified at.
        /// </summary>
        internal static string ModifiedAt {
            get {
                return ResourceManager.GetString("ModifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened at.
        /// </summary>
        internal static string OpenedAt {
            get {
                return ResourceManager.GetString("OpenedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened by.
        /// </summary>
        internal static string OpenedBy {
            get {
                return ResourceManager.GetString("OpenedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project title.
        /// </summary>
        internal static string ProjectTitle {
            get {
                return ResourceManager.GetString("ProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register author.
        /// </summary>
        internal static string RegisterAuthor {
            get {
                return ResourceManager.GetString("RegisterAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removable.
        /// </summary>
        internal static string Removable {
            get {
                return ResourceManager.GetString("Removable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        internal static string Responsible {
            get {
                return ResourceManager.GetString("Responsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible author.
        /// </summary>
        internal static string ResponsibleAuthor {
            get {
                return ResourceManager.GetString("ResponsibleAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached?.
        /// </summary>
        internal static string SolutionAttached {
            get {
                return ResourceManager.GetString("SolutionAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is solution database attached to SQL server?.
        /// </summary>
        internal static string SolutionAttachedDescription {
            get {
                return ResourceManager.GetString("SolutionAttachedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/time when the solution was created.
        /// </summary>
        internal static string SolutionCreatedAtDescription {
            get {
                return ResourceManager.GetString("SolutionCreatedAtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User, which created this solution.
        /// </summary>
        internal static string SolutionCreatedByDescription {
            get {
                return ResourceManager.GetString("SolutionCreatedByDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution name used to register solution database in an SQL server.
        /// </summary>
        internal static string SolutionDbNameDescription {
            get {
                return ResourceManager.GetString("SolutionDbNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution file (or catalog) name - without path and extension.
        /// </summary>
        internal static string SolutionFileNameDescription {
            get {
                return ResourceManager.GetString("SolutionFileNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution ID.
        /// </summary>
        internal static string SolutionID {
            get {
                return ResourceManager.GetString("SolutionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique solution identifier (set by server).
        /// </summary>
        internal static string SolutionIdDescription {
            get {
                return ResourceManager.GetString("SolutionIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution database kind.
        /// </summary>
        internal static string SolutionKind {
            get {
                return ResourceManager.GetString("SolutionKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution database engine name (database management system).
        /// </summary>
        internal static string SolutionKindDescription {
            get {
                return ResourceManager.GetString("SolutionKindDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/time when the solution was last modified.
        /// </summary>
        internal static string SolutionModifiedAtDescription {
            get {
                return ResourceManager.GetString("SolutionModifiedAtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution name.
        /// </summary>
        internal static string SolutionName {
            get {
                return ResourceManager.GetString("SolutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution internal name (used by SQL server).
        /// </summary>
        internal static string SolutionNameDescription {
            get {
                return ResourceManager.GetString("SolutionNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors registered for this solution.
        /// </summary>
        internal static string SolutionRegisteredAuthorsDescription {
            get {
                return ResourceManager.GetString("SolutionRegisteredAuthorsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered author responsible for the solution.
        /// </summary>
        internal static string SolutionResponsibleAuthorDescription {
            get {
                return ResourceManager.GetString("SolutionResponsibleAuthorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stereotype.
        /// </summary>
        internal static string Stereotype {
            get {
                return ResourceManager.GetString("Stereotype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        internal static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;unknown&gt;.
        /// </summary>
        internal static string UnknownKind {
            get {
                return ResourceManager.GetString("UnknownKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI.
        /// </summary>
        internal static string URI {
            get {
                return ResourceManager.GetString("URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI string.
        /// </summary>
        internal static string URIString {
            get {
                return ResourceManager.GetString("URIString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date when this version was closed.
        /// </summary>
        internal static string VersionClosedAtDescription {
            get {
                return ResourceManager.GetString("VersionClosedAtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The author who closed this version.
        /// </summary>
        internal static string VersionClosedByDescription {
            get {
                return ResourceManager.GetString("VersionClosedByDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document version creation date and time.
        /// </summary>
        internal static string VersionCreatedAtDescription {
            get {
                return ResourceManager.GetString("VersionCreatedAtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document version author&apos;s identifier.
        /// </summary>
        internal static string VersionCreatedByDescription {
            get {
                return ResourceManager.GetString("VersionCreatedByDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version ID identifies iteration, phase and bucket.
        /// </summary>
        internal static string VersionIDDescription {
            get {
                return ResourceManager.GetString("VersionIDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the version closed?.
        /// </summary>
        internal static string VersionIsClosedDescription {
            get {
                return ResourceManager.GetString("VersionIsClosedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date when this version was opened.
        /// </summary>
        internal static string VersionOpenedAtDescription {
            get {
                return ResourceManager.GetString("VersionOpenedAtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The author who opened this version.
        /// </summary>
        internal static string VersionOpenedByDescription {
            get {
                return ResourceManager.GetString("VersionOpenedByDescription", resourceCulture);
            }
        }
    }
}
