//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iml.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Iml.Resources.DataErrors", typeof(DataErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        public static string AdminAccess {
            get {
                return ResourceManager.GetString("AdminAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to add empty item to {0} collection.
        /// </summary>
        public static string AttemptToAddEmptyItemToCollection_1 {
            get {
                return ResourceManager.GetString("AttemptToAddEmptyItemToCollection_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author &quot;{0}&quot; already exists.
        /// </summary>
        public static string AuthorAlreadyExists_1 {
            get {
                return ResourceManager.GetString("AuthorAlreadyExists_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author &quot;{0}&quot; not registered in project &quot;{1}&quot;.
        /// </summary>
        public static string AuthorNotRegisteredInProject_2 {
            get {
                return ResourceManager.GetString("AuthorNotRegisteredInProject_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author &quot;{0}&quot; not registered in solution &quot;{1}&quot;.
        /// </summary>
        public static string AuthorNotRegisteredInSolution_2 {
            get {
                return ResourceManager.GetString("AuthorNotRegisteredInSolution_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t change element &quot;{0}&quot; at layer &quot;{1}&quot; which is lower than element&apos;s original layer &quot;{2}&quot;.
        /// </summary>
        public static string CantChangeElementAtLowerLayer_3 {
            get {
                return ResourceManager.GetString("CantChangeElementAtLowerLayer_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create database &quot;{0}&quot;.
        /// </summary>
        public static string CantCreateDatabase_1 {
            get {
                return ResourceManager.GetString("CantCreateDatabase_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create table &quot;{0}&quot;.
        /// </summary>
        public static string CantCreateTable_1 {
            get {
                return ResourceManager.GetString("CantCreateTable_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create table(s) in database &quot;{0}&quot;.
        /// </summary>
        public static string CantCreateTablesInDatabase_1 {
            get {
                return ResourceManager.GetString("CantCreateTablesInDatabase_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete author &quot;{0}&quot;. Author was active..
        /// </summary>
        public static string CantDeleteActiveAuthor_1 {
            get {
                return ResourceManager.GetString("CantDeleteActiveAuthor_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete database &quot;{0}&quot;.
        /// </summary>
        public static string CantDeleteDatabase_1 {
            get {
                return ResourceManager.GetString("CantDeleteDatabase_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete non empty document &quot;{0}&quot;.
        /// </summary>
        public static string CantDeleteNonEmptyDocument_1 {
            get {
                return ResourceManager.GetString("CantDeleteNonEmptyDocument_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete non empty layer &quot;{0}&quot;.
        /// </summary>
        public static string CantDeleteNonEmptyLayer_1 {
            get {
                return ResourceManager.GetString("CantDeleteNonEmptyLayer_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete non empty project &quot;{0}&quot;.
        /// </summary>
        public static string CantDeleteNonEmptyProject_1 {
            get {
                return ResourceManager.GetString("CantDeleteNonEmptyProject_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete used namespace &quot;{0}&quot;.
        /// </summary>
        public static string CantDeleteUsedNamespace_1 {
            get {
                return ResourceManager.GetString("CantDeleteUsedNamespace_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionOpeningTimedOut.
        /// </summary>
        public static string ConnectionOpeningTimedOut {
            get {
                return ResourceManager.GetString("ConnectionOpeningTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database &quot;{0}&quot; read error.
        /// </summary>
        public static string DatabaseReadError_1 {
            get {
                return ResourceManager.GetString("DatabaseReadError_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database &quot;{0}&quot; write error.
        /// </summary>
        public static string DatabaseWriteError_1 {
            get {
                return ResourceManager.GetString("DatabaseWriteError_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document &quot;{0}&quot; not found in layer &quot;{1}&quot;.
        /// </summary>
        public static string DocumentNotFoundInLayer_2 {
            get {
                return ResourceManager.GetString("DocumentNotFoundInLayer_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document &quot;{0}&quot; not found in solution &quot;{1}&quot;.
        /// </summary>
        public static string DocumentNotFoundInSolution_2 {
            get {
                return ResourceManager.GetString("DocumentNotFoundInSolution_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate value &quot;{0}&quot; for unique property &quot;{1}&quot;.
        /// </summary>
        public static string DuplicateValueForUniqueProperty_2 {
            get {
                return ResourceManager.GetString("DuplicateValueForUniqueProperty_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author&apos;s ID must not be empty.
        /// </summary>
        public static string EmptyAuthorID {
            get {
                return ResourceManager.GetString("EmptyAuthorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer ID must not be empty.
        /// </summary>
        public static string EmptyLayerID {
            get {
                return ResourceManager.GetString("EmptyLayerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &quot;{1}&quot; delete error.
        /// </summary>
        public static string EntityDeleteError_2 {
            get {
                return ResourceManager.GetString("EntityDeleteError_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &quot;{1}&quot; insert error.
        /// </summary>
        public static string EntityInsertError_2 {
            get {
                return ResourceManager.GetString("EntityInsertError_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &quot;{1}&quot; update error.
        /// </summary>
        public static string EntityUpdateError_2 {
            get {
                return ResourceManager.GetString("EntityUpdateError_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive access key for user &quot;{0}&quot;.
        /// </summary>
        public static string InactiveAccessKey_1 {
            get {
                return ResourceManager.GetString("InactiveAccessKey_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index &quot;{0}&quot; key can&apos;t be null.
        /// </summary>
        public static string IndexKeyCantBeNull_1 {
            get {
                return ResourceManager.GetString("IndexKeyCantBeNull_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid (empty) access key.
        /// </summary>
        public static string InvalidAccessKey {
            get {
                return ResourceManager.GetString("InvalidAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid access key for user &quot;{0}&quot;.
        /// </summary>
        public static string InvalidAccessKey_1 {
            get {
                return ResourceManager.GetString("InvalidAccessKey_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid item type {0}.
        /// </summary>
        public static string InvalidItemType_1 {
            get {
                return ResourceManager.GetString("InvalidItemType_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer ID &quot;{0}&quot; is invalid.
        /// </summary>
        public static string InvalidLayerID_1 {
            get {
                return ResourceManager.GetString("InvalidLayerID_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{0}&quot; has no {1} access.
        /// </summary>
        public static string InvalidUserAccess_2 {
            get {
                return ResourceManager.GetString("InvalidUserAccess_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Xml element name &quot;{0}&quot;. &quot;{1}&quot; expected..
        /// </summary>
        public static string InvalidXmlElementName_2 {
            get {
                return ResourceManager.GetString("InvalidXmlElementName_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration &quot;{0}&quot; not found.
        /// </summary>
        public static string IterationNotFound_1 {
            get {
                return ResourceManager.GetString("IterationNotFound_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key expired.
        /// </summary>
        public static string KeyExpired {
            get {
                return ResourceManager.GetString("KeyExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer &quot;{0}&quot; already exists.
        /// </summary>
        public static string LayerAlreadyExists_1 {
            get {
                return ResourceManager.GetString("LayerAlreadyExists_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer &quot;{0} is closed.
        /// </summary>
        public static string LayerIsClosed_1 {
            get {
                return ResourceManager.GetString("LayerIsClosed_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer &quot;{0} does not represent iteration.
        /// </summary>
        public static string LayerIsNotIteration_1 {
            get {
                return ResourceManager.GetString("LayerIsNotIteration_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer &quot;{0}&quot; not found in solution &quot;{1}&quot;.
        /// </summary>
        public static string LayerNotFoundInSolution_2 {
            get {
                return ResourceManager.GetString("LayerNotFoundInSolution_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer &quot;{0}&quot; template not found.
        /// </summary>
        public static string LayerTemplateNotFound_1 {
            get {
                return ResourceManager.GetString("LayerTemplateNotFound_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;ProjectSymbol&quot; attribute missing in &quot;{0}&quot; document element.
        /// </summary>
        public static string MissingProjectSymbol_1 {
            get {
                return ResourceManager.GetString("MissingProjectSymbol_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace &quot;{0}&quot; already exists.
        /// </summary>
        public static string NamespaceAlreadyExists_1 {
            get {
                return ResourceManager.GetString("NamespaceAlreadyExists_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace &quot;{0}&quot; not found in solution &quot;{1}&quot;.
        /// </summary>
        public static string NamespaceNotFoundInSolution_2 {
            get {
                return ResourceManager.GetString("NamespaceNotFoundInSolution_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New author can change element &quot;{0}&quot; only at layer higher than &quot;{1}&quot;.
        /// </summary>
        public static string NewAuthorCanChangeElementOnlyAtHigherLayer_2 {
            get {
                return ResourceManager.GetString("NewAuthorCanChangeElementOnlyAtHigherLayer_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No root node in a XML document.
        /// </summary>
        public static string NoRootNodeInXmlDocument {
            get {
                return ResourceManager.GetString("NoRootNodeInXmlDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No version found for layer &quot;{0}&quot;.
        /// </summary>
        public static string NoVersionFoundForLayer_1 {
            get {
                return ResourceManager.GetString("NoVersionFoundForLayer_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase &quot;{0}&quot; not found.
        /// </summary>
        public static string PhaseNotFound_1 {
            get {
                return ResourceManager.GetString("PhaseNotFound_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary index already exists in table &quot;{0}&quot;.
        /// </summary>
        public static string PrimaryIndexAlreadyExistsInTable_1 {
            get {
                return ResourceManager.GetString("PrimaryIndexAlreadyExistsInTable_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key already exists in table &quot;{0}&quot;.
        /// </summary>
        public static string PrimaryKeyAlreadyExistsInTable_1 {
            get {
                return ResourceManager.GetString("PrimaryKeyAlreadyExistsInTable_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key &quot;{0}&quot; violation for &quot;{0}&quot;.
        /// </summary>
        public static string PrimaryKeyViolation_1 {
            get {
                return ResourceManager.GetString("PrimaryKeyViolation_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project &quot;{0}&quot; not found in solution &quot;{1}&quot;.
        /// </summary>
        public static string ProjectNotFoundInSolution_2 {
            get {
                return ResourceManager.GetString("ProjectNotFoundInSolution_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property file for database &quot;{0}&quot; not found.
        /// </summary>
        public static string PropertyFileToFound_1 {
            get {
                return ResourceManager.GetString("PropertyFileToFound_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read.
        /// </summary>
        public static string ReadAccess {
            get {
                return ResourceManager.GetString("ReadAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; is read only.
        /// </summary>
        public static string ReadOnlyProperty_1 {
            get {
                return ResourceManager.GetString("ReadOnlyProperty_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich text &quot;{0}&quot; parse error at position {1}.
        /// </summary>
        public static string RichTextParseErrorAtPos_2 {
            get {
                return ResourceManager.GetString("RichTextParseErrorAtPos_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized connection state: &quot;{0}&quot;.
        /// </summary>
        public static string UnrecognizedConnectionState_1 {
            get {
                return ResourceManager.GetString("UnrecognizedConnectionState_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized Xml attribute value {0}=&quot;{1}&quot;.
        /// </summary>
        public static string UnrecognizedXmlAttributeValue_2 {
            get {
                return ResourceManager.GetString("UnrecognizedXmlAttributeValue_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized Xml element &quot;{0}&quot;.
        /// </summary>
        public static string UnrecognizedXmlElement_1 {
            get {
                return ResourceManager.GetString("UnrecognizedXmlElement_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &quot;{0}&quot; for property &quot;{1}&quot; can&apos;t be changed.
        /// </summary>
        public static string ValueForPropertyCantBeChanged_2 {
            get {
                return ResourceManager.GetString("ValueForPropertyCantBeChanged_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value fo property &quot;{0}&quot; can&apos;t be empty.
        /// </summary>
        public static string ValueForPropertyCantBeEmpty_1 {
            get {
                return ResourceManager.GetString("ValueForPropertyCantBeEmpty_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &quot;{0}&quot; for property &quot;{1}&quot; is already used.
        /// </summary>
        public static string ValueForPropertyIsAlreadyUsed_2 {
            get {
                return ResourceManager.GetString("ValueForPropertyIsAlreadyUsed_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to write.
        /// </summary>
        public static string WriteAccess {
            get {
                return ResourceManager.GetString("WriteAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading XML file &quot;{0}&quot;.
        /// </summary>
        public static string XmlFileReadError_1 {
            get {
                return ResourceManager.GetString("XmlFileReadError_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing XML file &quot;{0}&quot;.
        /// </summary>
        public static string XmlFileWriteError_1 {
            get {
                return ResourceManager.GetString("XmlFileWriteError_1", resourceCulture);
            }
        }
    }
}
